baseURL = "/"
languageCode = "en-gb"
title = "Murray Groves"
theme = "personal-web"
copyright="© Murray Groves"
googleAnalytics = "UA-153520490-1"
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, I'm Murray"
  sub = "I'm a primarily Python Developer who's interested in data processing and wants to learn more languages."

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#112F41"
  mainSections = ['portfolio']

[params.notFound]
  gopher = "https://cdn1.iconfinder.com/data/icons/cute-line-robot/32/cute_robot_emoji_sad_avatar_machine_emoticon-512.png"
  h1 = 'Unfortunately, the page you requested could not be found.'
  p = "It seems that this page doesn't exist."

[params.sections]
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = 'https://i.imgur.com/NzjiOzW.jpg'
  gradientOverlay = ''
  logo = "https://vignette.wikia.nocookie.net/half-life/images/7/7f/Aperture_Science_yellow_monitor.svg/revision/latest/zoom-crop/width/240/height/240?cb=20091023150453&path-prefix=en"

[params.assets]
  favicon = "https://imgur.com/0jdRmsQ.png"
  customCSS = "syntax.min.css"

[params.social]
  github = ""
  instagram = ""

[params.contact]
  email = "murray@thegrovesfamily.net"
  text= "Email Me"


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = false
